SELECT 'agents' as tbl, count(*) FROM agents
UNION ALL SELECT 'campaigns', count(*) FROM campaigns
UNION ALL SELECT 'call_logs', count(*) FROM call_logs
UNION ALL SELECT 'prompt_templates', count(*) FROM prompt_templates
UNION ALL SELECT 'number_lists', count(*) FROM number_lists
UNION ALL SELECT 'phone_numbers', count(*) FROM phone_numbers
UNION ALL SELECT 'dial_lists', count(*) FROM dial_lists
UNION ALL SELECT 'dial_list_entries', count(*) FROM dial_list_entries
UNION ALL SELECT 'leads', count(*) FROM leads
UNION ALL SELECT 'appointments', count(*) FROM appointments
UNION ALL SELECT 'survey_responses', count(*) FROM survey_responses
UNION ALL SELECT 'sip_trunks', count(*) FROM sip_trunks
UNION ALL SELECT 'knowledge_bases', count(*) FROM knowledge_bases
UNION ALL SELECT 'system_settings', count(*) FROM system_settings
UNION ALL SELECT 'webhook_endpoints', count(*) FROM webhook_endpoints
UNION ALL SELECT 'api_keys', count(*) FROM api_keys
UNION ALL SELECT 'users', count(*) FROM users
UNION ALL SELECT 'dnc_list', count(*) FROM dnc_list
ORDER BY 1;
